name: CI Pipeline

on:
  push:
    branches:
      - main
    # Optional: chỉ chạy khi có thay đổi trong thư mục cụ thể
    # paths:
    #   - 'src/**'
    #   - 'tests/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show commit info
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Commit by: ${{ github.event.head_commit.author.name }}"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run tests (headed mode)
        run: xvfb-run npx playwright test --headed
